matrix:
  include:
    - language: python
      python: 3.8
      script:
      - pip3 install pipenv
      - pipenv install

    - language: node_js
      node_js: 
      - "10"
      script:
      - cd Back
      - yarn install
      - yarn build
      - yarn start
