matrix:
  include:
    - language: python
      python: 3.6
      script:
      - pip3 install pipenv
      - pipenv install

    - language: node_js
      node_js: 
      - "10"
      script:
      - yarn install
